### ISSUE TITLE
Thread Safety of Gentleman instance

### ISSUE THREAD

**Issue by sachinwalia2k8** [h2non/gentleman#38] opened 2017-11-08 16:54 UTC
I am wondering if one instance of Gentleman can be shared across multiple go-routines Or every go-routine should create it's own instance every time a request comes?

**Comment by h2non** [comment] 2017-11-08 17:56
Thread safety is not fully built-in in the package, but global API surface, such as the middleware layer, should provide thread safety guarantees. However, gentleman's context does not, since every outoing request it's expected to be executed within a single coroutine context.

The typical approach here would be creating a new `Request` instance every time you want to perform a request.

**Comment by sachinwalia2k8** [comment] 2017-11-08 18:01
Thanks @h2non. So if I create cli instance and share it then seems like it is fine:

//create once during server startup
  cli := gentleman.New()

//create request in each go-routine
  req := cli.Request()

Also If I want to setup middlewares / plugins (such as retry, headers, compression) for cli then it can be set globally as well?

**Comment by h2non** [comment] 2017-11-08 18:04
Yes, you can. The middleware layer is hierarchical by design. You can register plugins at global level that would be executed on every outgoing request from that client. E.g:

```go
cli := gentleman.New()
cli.Use(retry)
cli.Use(compression)

// Create request in each go-routine
req := cli.Request()
```

**Comment by sachinwalia2k8** [comment] 2017-11-08 18:34
thanks @h2non this is very helpful.

**Comment by sachinwalia2k8** [comment] 2017-11-08 18:34
thanks @h2non this is very helpful.

**Comment by h2non** [comment] 2017-11-08 19:16
Your welcome. I'm going to close the issue for now.

**Closed by h2non** 2017-11-08 19:16 UTC
Labels: question
